### ISSUE TITLE
Sidebar?

### ISSUE THREAD

**Issue by Kloptoe** [Tronic247/material#26]
Having a sidebar would be awesome, with features like:

<li>the sidebar can be positioned on <strong>top</strong>, <strong>bottom</strong>, <strong>left</strong>, <strong>right</strong></li>
<br>
<li>Being able to change the sidebar animation</li>
<br>
<li>Sidebar can be hidden when it hits a certain size like mobile and can be opened with a trigger, sidebar could also be just hidden and just can be opened by a trigger.</li>

**Comment by Tronic247** [comment]
I'm still writing the docs for that.

**Comment by Kloptoe** [comment]
Awesome! 
<br>
<small>Also, thank you for making this! You've been doing too good to stop now</small>

**Comment by Kloptoe** [comment]
<small><strong>If you need a helper for CSS, I can help a bit</strong></small>

**Comment by Tronic247** [comment]
@Kloptoe okay :D

**Comment by Tronic247** [comment]
@Kloptoe If you need a demo see it here , any bugs are welcome ;D [https://jsfiddle.net/Lyas6ebt/1/embedded/result](https://jsfiddle.net/Lyas6ebt/1/embedded/result)

**Comment by wolf-yuan-6115** [comment]
> @Kloptoe If you need a demo see it here , any bugs are welcome ;D https://jsfiddle.net/Lyas6ebt/1/embedded/result

Sidebar cannot be closed on mobile

**Comment by Tronic247** [comment]
@wolf-yuan-6115 what do you mean ? please explain.

**Comment by wolf-yuan-6115** [comment]
> @wolf-yuan-6115 what do you mean ? please explain.

Open https://jsfiddle.net/Lyas6ebt/1/embedded/result on mobile,  press trigger or something else that will open sidebar, there is no way to close that sidebar.
I can't remember what button is it

**Comment by Tronic247** [comment]
@wolf-yuan-6115 here It is https://jsfiddle.net/2taxnpj1/. **And if you like this framework don't forget to give it a star and spread the word :D.**

**Comment by Tronic247** [comment]
@Kloptoe since you are in discord I'll lock the issue.
