### ISSUE TITLE
Restore CI build

### ISSUE THREAD

**Issue by Stylix58** [Tronic247/material#28]
I have see you have deleted the build. Can you explain why and, if you say yes, restore it?

PS: If you want a build for development and not for production, just create a another branch and change trigger condition based on GitHub's docs!

**Comment by Tronic247** [comment]
Because I need to prefix the compiled files

**Comment by Stylix58** [comment]
You can search a solution before destroying everthing?

**Comment by Tronic247** [comment]
@Stylix58  Do you know a solution ?

**Comment by Stylix58** [comment]
> PS: If you want a build for development and not for production, just create a another branch and change trigger condition based on GitHub's docs!

see this

**Comment by Tronic247** [comment]
@Stylix58 No need thank you anyway

**Comment by Tronic247** [comment]
test

**Comment by Tronic247** [comment]
test
