### ISSUE TITLE
New Components and features

### ISSUE THREAD

**Issue by Kloptoe** [Tronic247/material#3]
Having Tooltips, tabs, grid, dropdown that did not rely on being clicked by the same trigger (being able to click off dropdown to close would be nice), Collapsible would be also nice to have in here. Would be really cool to have to make this even better

**Comment by Tronic247** [comment]
Thank you for your support. These all features are being added in v2 (Coming Soon).

**Comment by Tronic247** [comment]
**@Kloptoe** I have released **v2.0 beta**. _Any feedback on that would be appreciated._

**Comment by Tronic247** [comment]
I am closing this issue because no respond. Good day :D
