### ISSUE TITLE
Make docs open-source

### ISSUE THREAD

**Issue by Stylix58** [Tronic247/material#4]
**Is your feature request related to a problem? Please describe.**
I would like to contribute to the framework and his documentation, but the documentation is source-closed.

**Describe the solution you'd like**
Make the documentation open-source.

**Additional context**
Choose a permissive license, like the project's license or an license thinked for written things, like the [Creative Commons license](https://creativecommons.org). You can also make a separate repository for the docs.

**Comment by Tronic247** [comment]
I have Created a new respiratory you can see it [Here](https://github.com/Tronic247/tronic247-material-docs/tree/main). <br>Still Working on the new documentation.<br> If you have to add or change something please send a PR to that respiratory with the component name.<br>`` ex- buttons; Create a new markdown file and write the contents should be there.  in markdown ``
Thank you very much for your support.

**Comment by Stylix58** [comment]
Ok!

**Comment by Tronic247** [comment]
No need to close issue :D others must see this.

**Comment by Tronic247** [comment]
@Stylix58 **_I am now making docs for the v2_**. **Can you help me by sending PR** to  that respiratory?

**Comment by Stylix58** [comment]
> @Stylix58 **_I am now making docs for the v2_**. **Can you help me by sending PR** to that respiratory?

(Pls say "repository") Yes, but this night.

**Comment by Tronic247** [comment]
@Stylix58 you just changed everything ! oh no I typed respiratory instead of repository :{

**Comment by Tronic247** [comment]
![image](https://user-images.githubusercontent.com/76736580/124377751-36c0aa00-dccb-11eb-97e6-0ccc8b2fa4be.png)
This is the new home page what should I change ? (The respiratory word is fixed)

**Comment by Stylix58** [comment]
It is cool! You should just fix the footer to the bottom of the page.

**Comment by Stylix58** [comment]
Also, you can see this for remove the blue highlight of buttons on mobile!
https://stackoverflow.com/a/45050338

**Comment by Tronic247** [comment]
In V2 all of the bugs are fixed :D

**Comment by Tronic247** [comment]
Also you can try the theme generator https://tronic247-material.web.app/theme-generator/ (Beta)

**Comment by Stylix58** [comment]
You should also make a Discord server!

**Comment by Tronic247** [comment]
> 
> 
> You should also make a Discord server!

I'm not on discord :( but I'm on gitter https://gitter.im/Tronic247-Material/community

**Comment by Stylix58** [comment]
You can join it please?
https://discord.com/

**Comment by Tronic247** [comment]
Sorry I don't like discord.

**Comment by Tronic247** [comment]
How is the new docs ? https://tronic247.github.io/tronic247-material-docs/index.html
