### ISSUE TITLE
does this need complete jQuery?

### ISSUE THREAD

**Issue by Rajaniraiyn** [Tronic247/material#44]
## Hi Guys!

This is a awesome project.

I understand that this **material**  is dependent on jQuery.

I replaced the [jQuery](https://code.jquery.com/jquery-3.6.0.min.js) with j[Query Slim](https://code.jquery.com/jquery-3.6.0.min.js). [here](http://jsfiddle.net/vpg6wudm/1/) everything seems to work perfectly.

If this only requires jQuery Slim then it will be awesome as it is lightweight as compared to jQuery.

I just want to confirm that.

**Comment by Tronic247** [comment]
Great news ! You can use jquery slim instead of the full jquery library.
