### ISSUE TITLE
CDN not working according to the official documentation.

### ISSUE THREAD

**Issue by inao-cz** [Tronic247/material#52]
**Describe the bug**
Link to CDN used in official documentation is broken thanks to the changed folder structure under dist/

**To Reproduce**
Try to use CDN link. It's unable to fetch (https://cdn.jsdelivr.net/gh/tronic247/material/dist/css/material.min.css)

**Expected behavior**
Well, obviously it should be fetched from CDN but CDN will return 404

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Can be fixed either by returning the old folder structure or by fixing the link in documentation to https://cdn.jsdelivr.net/gh/tronic247/material/dist/material.min.css - removed /css since folder css doesn't exist.

**Comment by Posandu** [comment]
This issue will be patched soon. Until then here are the links.
## JS
```
https://unpkg.com/tronic247-material@3.0.0/dist/material.min.js
```
## CSS
```
https://unpkg.com/tronic247-material@3.0.0/dist/material.min.css
````

**Comment by Posandu** [comment]
Fixed

**Comment by jimaek** [comment]
You use the same format for jsDelivr too https://cdn.jsdelivr.net/npm/tronic247-material@3.0.0/dist/material.min.js
